# <font color=blue>Assignments for "Main Statistical Concepts"</font>

Please upload your solutions to the following assignments as Jupyter Notebook to your GitHub account and share the GitHub link with the button below. You can talk to your mentor about the issues you have in mind or ask Slack at office time.

1. Analyze the central tendency and distribution measurements with the mathematical formula given above and the built-in codes available in python through 3 different data that you will generate using the numpy library !!!

In [1]:
import numpy as np
import pandas as pd
import statistics

## First Dataset Randomly Generated From Normal Distribution $ N (70,64) $

In [2]:
random1=np.random.normal(70,8,100)
random1

array([65.83777567, 75.56478319, 72.22972892, 62.25051619, 59.50591443,
       78.39090004, 76.24759816, 71.38027398, 71.08268864, 84.61663467,
       73.70281118, 57.53703162, 66.01923336, 66.21577464, 80.18218379,
       58.87984303, 73.05817772, 48.3273155 , 68.10257045, 76.49039812,
       78.78397042, 73.68584331, 69.56015287, 75.81894221, 65.20429172,
       65.23809639, 52.12872395, 76.83733191, 66.39591757, 71.36054191,
       81.12667462, 78.63574646, 63.40805362, 74.42267799, 80.61926744,
       61.54207952, 61.02143432, 75.31188151, 68.35466793, 81.16045145,
       56.7616322 , 71.04476651, 77.05445266, 68.47549407, 60.85988726,
       74.22628619, 82.89653477, 76.11990728, 61.89331971, 79.46249129,
       66.47663604, 74.1393726 , 67.44671206, 60.67239284, 71.00405979,
       65.08867317, 55.20307689, 69.87295764, 63.36757268, 62.4691534 ,
       68.97161223, 60.66587022, 61.29226663, 74.7366233 , 72.61213838,
       71.66792237, 89.82896766, 77.47271121, 56.82254933, 58.98

### Central Tendency Measurements for First Dataset:

In [3]:
print("The mean of 'First Dataset': {:06.4f}.".format(np.mean(random1)))
print("The median of 'First Dataset': {:06.4f}.".format(np.median(random1)))
print("The mode of 'First Dataset': {:06.4f}.".format(statistics.mode(random1)))

The mean of 'First Dataset': 70.0472.
The median of 'First Dataset': 71.0244.
The mode of 'First Dataset': 65.8378.


### Dispersion Measurements for First Dataset:

In [4]:
print("The variance of 'First Dataset': {:06.4f}.".format(np.var(random1)))
print("The standard deviation of 'First Dataset': {:06.4f}.".format(np.std(random1,ddof=1)))
print("The standard error of 'First Dataset': {:06.4f}.".format(np.std(random1,ddof=1)/np.sqrt(len(random1))))

The variance of 'First Dataset': 63.6800.
The standard deviation of 'First Dataset': 8.0202.
The standard error of 'First Dataset': 0.8020.


## Second Dataset Randomly Generated From Standart Normal Distibution $N(0,1)$

In [5]:
random2=np.random.normal(0,1,100)
random2

array([-1.57574784,  0.44784568, -1.60031068,  0.02834515,  1.48994528,
        2.1687208 , -1.17824279, -1.41455316, -0.09698841,  2.15742078,
       -0.31799928, -0.24406387, -1.16804031,  0.51269272, -1.46170203,
        0.40850823,  0.85679995, -0.21656687, -1.30745953,  0.79735455,
       -1.16646341,  0.53451372,  0.58664493,  0.03274597,  0.20966394,
        0.90395688,  1.72220695, -0.03616256,  0.55718806, -1.40867551,
       -1.03392822,  0.08165828, -0.0548478 , -0.46548554, -0.0129837 ,
       -0.93239816, -0.0931089 , -0.3468375 , -0.56357655, -0.8112857 ,
       -0.81284559, -0.55295482, -1.02665825,  1.75978433, -0.16041406,
       -1.53770219,  0.89312112,  1.46235578,  2.5349063 , -2.50448268,
        1.24325581,  0.7451526 , -0.916566  ,  0.04389756,  0.58712375,
       -0.90063962,  0.37136124, -0.62783423, -0.57604874,  0.33371194,
        0.40166743, -0.24704447, -0.50038222, -0.69644895,  0.63614213,
        1.088595  ,  0.15828027,  0.79346857, -0.40946984,  0.99

### Central Tendency Measurements for Second Dataset:

In [6]:
print("The mean of 'Second Dataset': {:06.4f}.".format(np.mean(random2)))
print("The median of 'Second Dataset': {:06.4f}.".format(np.median(random2)))
print("The mode of 'Second Dataset': {:06.4f}.".format(statistics.mode(random2)))

The mean of 'Second Dataset': 0.0022.
The median of 'Second Dataset': -0.0277.
The mode of 'Second Dataset': -1.5757.


### Dispersion Measurements for Second Dataset:

In [7]:
print("The variance of 'Second Dataset': {:06.4f}.".format(np.var(random2)))
print("The standard deviation of 'Second Dataset': {:06.4f}.".format(np.std(random2,ddof=1)))
print("The standard error of 'Second Dataset': {:06.4f}.".format(np.std(random2,ddof=1)/np.sqrt(len(random2))))

The variance of 'Second Dataset': 0.9833.
The standard deviation of 'Second Dataset': 0.9966.
The standard error of 'Second Dataset': 0.0997.


## Third Dataset Randomly Generated From Normal Distibution $𝑁(160,100)$

In [8]:
random3=np.round_(np.random.normal(160,10,100),0).astype(int)
random3

array([153, 163, 147, 157, 156, 155, 158, 156, 162, 175, 142, 157, 173,
       174, 171, 163, 163, 147, 164, 166, 153, 156, 172, 164, 157, 170,
       158, 176, 162, 151, 162, 165, 153, 161, 154, 161, 135, 150, 163,
       155, 158, 159, 176, 138, 142, 170, 155, 172, 155, 166, 160, 155,
       163, 156, 162, 157, 154, 178, 156, 144, 149, 164, 146, 163, 157,
       154, 168, 164, 179, 136, 170, 153, 145, 161, 143, 187, 147, 174,
       167, 155, 169, 168, 149, 165, 165, 152, 156, 160, 170, 154, 165,
       162, 157, 153, 166, 147, 158, 179, 153, 140])

### Central Tendency Measurements for Third Dataset:

In [9]:
print("The mean of 'Third Dataset': {:04.2f}.".format(np.mean(random3)))
print("The median of 'Third Dataset': {:04.2f}.".format(np.median(random3)))
print("The mode of 'Third Dataset': {:04.2f}.".format(statistics.mode(random3)))

The mean of 'Third Dataset': 159.26.
The median of 'Third Dataset': 158.00.
The mode of 'Third Dataset': 153.00.


### Dispersion Measurements for Third Dataset:

In [10]:
print("The variance of 'Third Dataset': {:04.2f}.".format(np.var(random3)))
print("The standard deviation of 'Third Dataset': {:02.2f}.".format(np.std(random3,ddof=1)))
print("The standard error of 'Third Dataset': {:04.2f}.".format(np.std(random3,ddof=1)/np.sqrt(len(random3))))

The variance of 'Third Dataset': 100.51.
The standard deviation of 'Third Dataset': 10.08.
The standard error of 'Third Dataset': 1.01.
