# <font color=blue>Assignments for "basics of NumPy Array"</font>

1. Create 3 lists representing house features, each list containing 10 values. First one for squaremeter of house, second one for rooms and last one for price. Then, create an array combining these lists.

In [1]:
import numpy as np
sq_house=[120,90,150,110,115,130,120,85,100,160]
room_house=[4,2,5,3,3,4,3,3,4,5]
price_house=[200000,120000,150000,115000,145000,160000,150000,100000,135000,250000]
House=np.array([sq_house,room_house,price_house])
House

array([[   120,     90,    150,    110,    115,    130,    120,     85,
           100,    160],
       [     4,      2,      5,      3,      3,      4,      3,      3,
             4,      5],
       [200000, 120000, 150000, 115000, 145000, 160000, 150000, 100000,
        135000, 250000]])

2. Transpose the array you have created, so that every line can represent features of one house.

In [2]:
House.T

array([[   120,      4, 200000],
       [    90,      2, 120000],
       [   150,      5, 150000],
       [   110,      3, 115000],
       [   115,      3, 145000],
       [   130,      4, 160000],
       [   120,      3, 150000],
       [    85,      3, 100000],
       [   100,      4, 135000],
       [   160,      5, 250000]])

3. Display the shape of the array and explain what it means.

In [3]:
House.T.shape

(10, 3)

In [4]:
print("There is information for {} houses in the dataset.".format(House.T.shape[0]))
print("There are {} attributes of each house.".format(House.T.shape[1]))

There is information for 10 houses in the dataset.
There are 3 attributes of each house.


4. Write a function that returns an array of ones with zeros where both row and column numbers are even. Sample array is below. Number of rows and columns will be entered as parameters.

```python
    shape(6 x 5) --> [[1   1   1   1   1]
                      [1   0   1   0   1]
                      [1   1   1   1   1]
                      [1   0   1   0   1]
                      [1   1   1   1   1]
                      [1   0   1   0   1]]
```

In [5]:
array_=np.ones((6,5))
array_
for i in range(1,7):
    for j in range(1,6):
         if (i%2==0) and (j%2==0):
            array_[i-1][j-1]=0
array_

array([[1., 1., 1., 1., 1.],
       [1., 0., 1., 0., 1.],
       [1., 1., 1., 1., 1.],
       [1., 0., 1., 0., 1.],
       [1., 1., 1., 1., 1.],
       [1., 0., 1., 0., 1.]])