# <font color=blue>Assignments for "Mathematical Operations on NumPy Arrays"</font>

1. Load the array you saved in the previous lesson from the disk.

In [1]:
import numpy as np
A=np.load('C:/Users/HANDEKONSUKUNLU/Documents/Data Science Course-wtech/earthquake_sliced.npy')
A

array([[ 1.    ,  1.    ,  1.    ,  1.    ,  1.    ],
       [ 0.    , 36.0535, 31.2135, 36.68  ,  5.2   ],
       [ 0.    , 37.1958, 30.6241, 50.33  ,  4.8   ],
       [ 0.    , 37.3773, 36.3855, 10.53  ,  4.8   ],
       [ 0.    , 35.8861, 26.0695, 28.49  ,  4.9   ],
       [ 0.    , 37.6546, 26.6698,  4.5   ,  4.5   ],
       [ 0.    , 37.5318, 29.848 , 17.58  ,  4.6   ],
       [ 0.    , 39.0388, 44.1533,  7.52  ,  4.5   ]])

2. Display the mean and the standard deviation for each column.

In [2]:
print("The mean of each columun: ",np.mean(A,axis=0))
print("The standard deviation of each columun: ",np.std(A,axis=0))

The mean of each columun:  [ 0.125     32.7172375 28.2454625 19.57875    4.2875   ]
The standard deviation of each columun:  [ 0.33071891 12.02314907 11.65057695 16.28392416  1.26138565]


3. Subtract 1, 25, 25, 10, 4 from columns in order. (Remember it can be subtracted in one line of code.)

In [3]:
B=np.array([1,25,25,10,4])
B

array([ 1, 25, 25, 10,  4])

In [4]:
C=A-B
C

array([[  0.    , -24.    , -24.    ,  -9.    ,  -3.    ],
       [ -1.    ,  11.0535,   6.2135,  26.68  ,   1.2   ],
       [ -1.    ,  12.1958,   5.6241,  40.33  ,   0.8   ],
       [ -1.    ,  12.3773,  11.3855,   0.53  ,   0.8   ],
       [ -1.    ,  10.8861,   1.0695,  18.49  ,   0.9   ],
       [ -1.    ,  12.6546,   1.6698,  -5.5   ,   0.5   ],
       [ -1.    ,  12.5318,   4.848 ,   7.58  ,   0.6   ],
       [ -1.    ,  14.0388,  19.1533,  -2.48  ,   0.5   ]])

4. Multiply each element by 2. (Remember it can be multiplied in one line of code.)

In [5]:
D=C*2
D

array([[  0.    , -48.    , -48.    , -18.    ,  -6.    ],
       [ -2.    ,  22.107 ,  12.427 ,  53.36  ,   2.4   ],
       [ -2.    ,  24.3916,  11.2482,  80.66  ,   1.6   ],
       [ -2.    ,  24.7546,  22.771 ,   1.06  ,   1.6   ],
       [ -2.    ,  21.7722,   2.139 ,  36.98  ,   1.8   ],
       [ -2.    ,  25.3092,   3.3396, -11.    ,   1.    ],
       [ -2.    ,  25.0636,   9.696 ,  15.16  ,   1.2   ],
       [ -2.    ,  28.0776,  38.3066,  -4.96  ,   1.    ]])