# <font color=blue>Assignments for "Indexing and Slicing of NumPy Arrays"</font>

For the assignment, you are going to use [Earthquakes](https://bootrain-lms-assets.s3.eu-central-1.amazonaws.com/bootrain-lms-static/datasets/Earthquakes.csv) dataset.

1. Load the Earthquakes dataset. Export the dataset to an array as you covered in the previous lesson.

In [1]:
import numpy as np
earthquake = np.genfromtxt('C:/Users/HANDEKONSUKUNLU/Documents/Data Science Course-wtech/Earthquakes.csv',delimiter=",")
earthquake.shape

(6574, 15)

2. Slice first 20 rows and column numbers 3, 5, 6, 7, 12. Then, assign the array you sliced to a variable.

In [2]:
A=earthquake[0:20,[3,5,6,7,12]]
A.shape

(20, 5)

In [3]:
A

array([[ 0.    , 36.8578, 44.4161, 16.97  ,  4.    ],
       [ 0.    , 37.4341, 35.852 ,  7.02  ,  4.1   ],
       [ 0.    , 37.6878, 37.4016, 10.27  ,  4.4   ],
       [ 0.    , 37.2003, 30.4376, 78.07  ,  4.    ],
       [ 0.    , 35.6846, 26.7266, 42.77  ,  4.5   ],
       [ 0.    , 36.4171, 28.6991, 14.86  ,  4.1   ],
       [ 0.    , 36.0535, 31.2135, 36.68  ,  5.2   ],
       [ 0.    , 37.1958, 30.6241, 50.33  ,  4.8   ],
       [ 0.    , 36.9653, 27.7633,  6.93  ,  4.3   ],
       [ 0.    , 38.893 , 26.4483, 11.62  ,  4.2   ],
       [ 0.    , 37.3773, 36.3855, 10.53  ,  4.8   ],
       [ 0.    , 35.8861, 26.0695, 28.49  ,  4.9   ],
       [ 0.    , 37.4635, 36.3113, 15.29  ,  4.3   ],
       [ 0.    , 37.0201, 36.0845, 10.    ,  4.1   ],
       [ 0.    , 37.6546, 26.6698,  4.5   ,  4.5   ],
       [ 0.    , 37.5318, 29.848 , 17.58  ,  4.6   ],
       [ 0.    , 39.0388, 44.1533,  7.52  ,  4.5   ],
       [ 0.    , 38.357 , 44.8686, 10.05  ,  4.1   ],
       [ 0.    , 35.7018, 28

3. Display the row numbers where last values are equal to 4.5 or higher.

In [4]:
A[A[:,4]>=4.5]

array([[ 0.    , 35.6846, 26.7266, 42.77  ,  4.5   ],
       [ 0.    , 36.0535, 31.2135, 36.68  ,  5.2   ],
       [ 0.    , 37.1958, 30.6241, 50.33  ,  4.8   ],
       [ 0.    , 37.3773, 36.3855, 10.53  ,  4.8   ],
       [ 0.    , 35.8861, 26.0695, 28.49  ,  4.9   ],
       [ 0.    , 37.6546, 26.6698,  4.5   ,  4.5   ],
       [ 0.    , 37.5318, 29.848 , 17.58  ,  4.6   ],
       [ 0.    , 39.0388, 44.1533,  7.52  ,  4.5   ]])

In [5]:
index=np.where(A[:,4]>=4.5)
print(index)

(array([ 4,  6,  7, 10, 11, 14, 15, 16], dtype=int64),)


In [6]:
B=A[index]

4. Assign 1 to first row.

In [7]:
B[0,]=1
B

array([[ 1.    ,  1.    ,  1.    ,  1.    ,  1.    ],
       [ 0.    , 36.0535, 31.2135, 36.68  ,  5.2   ],
       [ 0.    , 37.1958, 30.6241, 50.33  ,  4.8   ],
       [ 0.    , 37.3773, 36.3855, 10.53  ,  4.8   ],
       [ 0.    , 35.8861, 26.0695, 28.49  ,  4.9   ],
       [ 0.    , 37.6546, 26.6698,  4.5   ,  4.5   ],
       [ 0.    , 37.5318, 29.848 , 17.58  ,  4.6   ],
       [ 0.    , 39.0388, 44.1533,  7.52  ,  4.5   ]])

5. Save the final state of the array to disk. You are going to use this in the next assignment.

In [8]:
np.save('C:/Users/HANDEKONSUKUNLU/Documents/Data Science Course-wtech/earthquake_sliced.npy', B)